logger:
  file:
    path: /var/log/open5gs/amf.log

global:

amf:
  sbi:
    server:
      - address: amf-1.5gc.mnc002.mcc262.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc002.mcc262.3gppnetwork.org:80
  ngap:
    server:
      - address: amf-1.5gc.mnc002.mcc262.3gppnetwork.org
  access_control:
    - plmn_id:
        mcc: 262
        mnc: 02
    - plmn_id:
        mcc: 262
        mnc: 03
  guami:
    - plmn_id:
        mcc: 262
        mnc: 02
      amf_id:
        region: 1
        set: 1
  tai:
    - plmn_id:
        mcc: 262
        mnc: 02
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 262
        mnc: 02
      s_nssai:
        - sst: 1
          sd: 000001
  security:
      integrity_order : [ NIA2, NIA1, NIA0 ]
      ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
  amf_name: open5gs-amf-1
  time:
    t3512:
      value: 540
