logger:
  file:
    path: /var/log/open5gs/nssf.log

global:

nssf:
  sbi:
    server:
      - address: nssf.5gc.mnc002.mcc262.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc002.mcc262.3gppnetwork.org:80
      nsi:
        - uri: http://nrf.5gc.mnc002.mcc262.3gppnetwork.org:80
          s_nssai:
            sst: 1
            sd: 000001
