logger:
  file:
    path: /var/log/open5gs/pcf.log

global:

pcf:
  sbi:
    server:
      - address: pcf.5gc.mnc002.mcc262.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc002.mcc262.3gppnetwork.org:80
  policy:
    - plmn_id:
        mcc: 262
        mnc: 02
      slice:
        - sst: 1
          sd: 000001
          default_indicator: true
          session:
            - name: internet
              type: 1
              ambr:
                downlink:
                  value: 1
                  unit: 3
                uplink:
                  value: 1
                  unit: 3
              qos:
                index: 9
                arp:
                  priority_level: 8
                  pre_emption_vulnerability: 1
                  pre_emption_capability: 1
